import type { RawLinkedInPost } from "../types";

/** Curated public LinkedIn research — same workflow CGA used for their demo. */
const BEONE_SEED: RawLinkedInPost[] = [
  {
    id: "beone-1",
    headline: "One Save Changes Everything",
    text: 'At BeOne, we\'re stepping up to the moment and redefining what a "save" can truly represent. Be on the lookout, because One Save Changes Everything. 05.20.26',
    postType: "Video",
    publishedAt: new Date(Date.now() - 56 * 86400000).toISOString(),
    reactions: 160,
    comments: 1,
    reposts: 44,
  },
  {
    id: "beone-2",
    headline: "Q1 2026 Financial Results",
    text: "BeOne Medicines announces first quarter 2026 financial results and business updates. 5-page slideshow.",
    postType: "Document",
    publishedAt: new Date(Date.now() - 49 * 86400000).toISOString(),
    reactions: 145,
    comments: 1,
    reposts: 24,
  },
  {
    id: "beone-3",
    headline: "PD-1 Inhibitor Receives FDA Priority Review",
    text: "BeOne Medicines is pleased to announce the FDA has granted Priority Review for our PD-1 inhibitor in combination with HER2-directed antibody and chemotherapy for first-line treatment of HER2+ gastroesophageal adenocarcinoma.",
    postType: "Document",
    publishedAt: new Date(Date.now() - 42 * 86400000).toISOString(),
    reactions: 642,
    comments: 4,
    reposts: 63,
  },
  {
    id: "beone-4",
    headline: "Global Impact Celebration Sponsorship",
    text: "We're proud to recognize BeOne Medicines as a valued partner and sponsor of our Global Impact Celebration. 293 patients reached through our partnership.",
    postType: "Repost",
    publishedAt: new Date(Date.now() - 35 * 86400000).toISOString(),
    reactions: 133,
    comments: 2,
    reposts: 5,
  },
  {
    id: "beone-5",
    headline: "WM World Awareness Day",
    text: "Today is WM World Awareness Day. Join the IWMF and Global Partners across 21 countries as we work toward Stronger Together.",
    postType: "Repost",
    publishedAt: new Date(Date.now() - 32 * 86400000).toISOString(),
    reactions: 34,
    comments: 0,
    reposts: 4,
  },
  {
    id: "beone-6",
    headline: "2025 Responsible Business & Sustainability Report",
    text: "Advancing global health. Empowering colleagues. Innovating sustainably. Operating responsibly. 5 pages covering four key areas of focus.",
    postType: "Document",
    publishedAt: new Date(Date.now() - 28 * 86400000).toISOString(),
    reactions: 153,
    comments: 2,
    reposts: 14,
  },
  {
    id: "beone-7",
    headline: "Esophageal Cancer Awareness Poll",
    text: "True or false: by 2050, annual deaths from esophageal cancer worldwide are projected to increase by roughly 85% compared to 2022? (Answer: True · 87% of voters)",
    postType: "Poll",
    publishedAt: new Date(Date.now() - 21 * 86400000).toISOString(),
    reactions: 62,
    comments: 3,
    reposts: 2,
  },
  {
    id: "beone-8",
    headline: "Richard's Story",
    text: 'When you hear the words "you have cancer," everything changes. Meet Richard, who faced the uncertainty that comes with an esophageal cancer diagnosis.',
    postType: "Video",
    publishedAt: new Date(Date.now() - 14 * 86400000).toISOString(),
    reactions: 0,
    comments: 0,
    reposts: 0,
  },
  {
    id: "beone-9",
    headline: "The BeOne Patient Advocacy Council",
    text: "Patients and caregivers have lived experience no clinical dataset can capture. That's what drives the BeOne Patient Advocacy Council, where patients shape the work.",
    postType: "Video",
    publishedAt: new Date(Date.now() - 14 * 86400000).toISOString(),
    reactions: 139,
    comments: 1,
    reposts: 4,
  },
  {
    id: "beone-10",
    headline: "Voices of Leadership: Kristian Stubbs, Canada GM",
    text: "Meet Kristian Stubbs, our General Manager, Canada at BeOne. Driven by a personal connection to cancer, he is committed to expanding access in Canadian markets.",
    postType: "Document",
    publishedAt: new Date(Date.now() - 7 * 86400000).toISOString(),
    reactions: 225,
    comments: 7,
    reposts: 5,
  },
  {
    id: "beone-11",
    headline: "Cancer Support Community: Step Therapy",
    text: "For patients with blood cancers like CLL, step therapy policies imposed by insurers and PBMs can delay, deny, or disrupt access.",
    postType: "Repost",
    publishedAt: new Date(Date.now() - 7 * 86400000).toISOString(),
    reactions: 0,
    comments: 0,
    reposts: 0,
  },
  {
    id: "beone-12",
    headline: "Great Place to Work APAC",
    text: "We're proud to see our teams in Thailand, Malaysia, and Singapore each recognized with Great Place To Work accreditation.",
    postType: "Repost",
    publishedAt: new Date(Date.now() - 7 * 86400000).toISOString(),
    reactions: 301,
    comments: 2,
    reposts: 2,
  },
];

export async function fetchPostsFromSeed(): Promise<RawLinkedInPost[]> {
  return BEONE_SEED;
}
